addons:
  apt:
    packages: 
    - automake
    - autoconf
    - g++
    - libboost-dev
    - libssl-dev
    - libpcap-dev
    - libcairo2-dev
language: cpp
compiler: clang
install:
 - ./bootstrap.sh && ./configure && make
script:
 - make check
